### ISSUE TITLE
Share resources please

### ISSUE THREAD

**Issue by gaurav-gogia** [CemalUnal/Operating-Systems-Codes#1]
This is good. Can you please share where are you learning OS from? 

Thanks 😄

**Comment by CemalUnal** [comment]
Hi @DesmondANIMUS,

Actually I have created this repository when I was taking Operating Systems course in the college. So the problems and their solutions in this repository belongs to that course.

**Comment by gaurav-gogia** [comment]
Ow, okay, no problem!
